name: Flow UI Deployment

on: push

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Assume Role
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          output-credentials: true

      - name: Upload to Amazon S3
        use: Noelware/s3-action@2 # this can be `master` or a tagged release
        with:
            directories: dist
            access-key-id: ${{ steps.creds.outputs.aws-access-key-id }}
            secret-key: ${{ steps.creds.outputs.aws-secret-access-key }}
            region: eu-west-2
            bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}