name: Flow UI Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          envkey_VITE_COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          envkey_VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          envkey_VITE_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_VITE_FLOW_API_URL: https://flow-api-dev.nsar-tech.co.uk
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: npm run build

      - name: Assume Role
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          output-credentials: true
          role-skip-session-tagging: true

      - name: Upload to Amazon S3
        uses: a-sync/s3-uploader@master
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          FILE: ./dist
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
